window.riskList = [
    "Afghanistan",
    "Ägypten",
    "Albanien",
    "Algerien",
    "Angola",
    "Antigua und Barbuda",
    "Äquatorialguinea",
    "Argentinien",
    "Armenien",
    "Aserbaidschan",
    "Äthiopien",
    "Bahamas",
    "Bahrain",
    "Bangladesch",
    "Barbados",
    "Belarus",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivien",
    "Bosnia und Herzegowina",
    "Brasilien",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Chile",
    "Costa Rica",
    "Côte d'Ivoire",
    "Dominica",
    "Dominikanische Republik",
    "Dschibuti",
    "Ecuador",
    "El Salvador",
    "Eritrea",
    "Eswatini",
    "Gabun",
    "Gambia",
    "Ghana",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Indien",
    "Indonesien",
    "Irak",
    "Iran",
    "Israel",
    "Jamaika",
    "Jemen",
    "Kap Verde",
    "Kamerun",
    "Kasachstan",
    "Katar",
    "Kenia",
    "Kirgisistan",
    "Kolumbien",
    "Komoren",
    "Kongo DR",
    "Kongo Rep",
    "Korea (Volksrepublik)",
    "Kosovo",
    "Kuba",
    "Kuwait",
    "Lesotho",
    "Libanon",
    "Liberia",
    "Libyen",
    "Madagaskar",
    "Malawi",
    "Mali",
    "Marokko",
    "Mauretanien",
    "Mexiko",
    "Mongolei",
    "Mosambik",
    "Namibia",
    "Nepal",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Nordmazedonien",
    "Oman",
    "Pakistan",
    "Palästinensische Gebiete",
    "Panama",
    "Papua-Neuguinea",
    "Peru",
    "Philippinen",
    "Republik Moldau",
    "Ruanda",
    "Russische Föderation",
    "Saint Kitts und Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Sambia",
    "São Tomé und Príncipe",
    "Saudi Arabien",
    "Schweden",
    "Senegal",
    "Serbien",
    "Sierra Leone",
    "Simbabwe",
    "Somalia",
    "Sri Lanka",
    "Südafrika",
    "Sudan",
    "Südsudan",
    "Surinam",
    "Syrische Arabische Republik",
    "Tadschikistan",
    "Tansania",
    "Timor Leste (Osttimor)",
    "Togo",
    "Trinidad Tobago",
    "Tschad",
    "Türkei",
    "Turkmenistan",
    "Uganda",
    "Ukraine",
    "USA",
    "Usbekistan",
    "Venezuela",
    "Vereinigte Arabische Emirate",
    "Zentralafrikanische Republik"
];